FROM jascha/express-magic

ADD ./ /srv/hosts

RUN \
  cd /srv/hosts/localhost/public/js; \
  browserify bundle/index.js > main.js && \

EXPOSE |xport|
CMD cd /srv; NODE_ENV=|env| supervisor --harmony --extensions "node,js,jade,styl" app.js
